package nobel;

import java.util.List;

public class NoImagePortrait {
    public static final List<String> names = List.of(
        "Aaron Ciechanover",
        "Ahmed Zewail",
        "Allvar Gullstrand",
        "American Friends Service Committee",
        "Amnesty International",
        "Anne L’Huillier",
        "Aristide Briand",
        "Bengt I. Samuelsson",
        "Bernard L. Feringa",
        "Center for Civil Liberties",
        "Claude Cohen-Tannoudji",
        "Daniel L. McFadden",
        "Daron Acemoglu",
        "David Card",
        "Doctors Without Borders",
        "Donald J. Cram",
        "Douglas D. Osheroff",
        "Eric Kandel",
        "European Union",
        "Eyvind Johnson",
        "Friends Service Council",
        "Geoffrey Wilkinson",
        "George D. Snell",
        "Georges Charpak",
        "Gerard Debreu",
        "Giorgos Seferis",
        "Grameen Bank",
        "Günter Blobel",
        "H. Robert Horvitz",
        "Harry M. Markowitz",
        "Herbert C. Brown",
        "Institute of International Law",
        "Intergovernmental Panel on Climate Change",
        "International Atomic Energy Agency",
        "International Campaign to Abolish Nuclear Weapons",
        "International Campaign to Ban Landmines",
        "International Committee of the Red Cross",
        "International Labour Organization",
        "International Physicians for the Prevention of Nuclear War",
        "Jack Kilby",
        "Jack Steinberger",
        "James Tobin",
        "John Clarke",
        "John Macleod",
        "John Pople",
        "Juan Ramón Jiménez",
        "Klaus Hasselmann",
        "Konrad Bloch",
        "Konrad Lorenz",
        "League of Red Cross Societies",
        "Leland Hartwell",
        "Louis Renault",
        "Mario R. Capecchi",
        "Mario Vargas Llosa",
        "Memorial",
        "Menachem Begin",
        "Murray Gell-Mann",
        "Myron Scholes",
        "Nadine Gordimer",
        "Nansen International Office for Refugees",
        "Nathan Söderblom",
        "National Dialogue Quartet",
        "Nihon Hidankyo",
        "Office of the United Nations High Commissioner for Refugees",
        "Oliver Smithies",
        "Organisation for the Prohibition of Chemical Weapons",
        "Permanent International Peace Bureau",
        "Pugwash Conferences on Science and World Affairs",
        "Randy W. Schekman",
        "Richard E. Smalley",
        "Richard Stone",
        "Rita Levi-Montalcini",
        "Robert B. Wilson",
        "Robert Woodrow Wilson",
        "Rudolf Eucken",
        "Sir Chandrasekhara Venkata Raman",
        "Sir James W. Black",
        "Sir John B. Gurdon",
        "Stanley Cohen",
        "United Nations",
        "United Nations Children's Fund",
        "United Nations Peacekeeping Forces",
        "Verner von Heidenstam",
        "Walter Gilbert",
        "William Vickrey",
        "World Food Programme"
    );
}