package wikidata.countries;

import wikidata.WikidataEntity;
import wikidata.WikidataEntityFilter;

public class CountryGeoEntityFilter implements WikidataEntityFilter {

    @Override
    public boolean accept(WikidataEntity e) {
        if (e == null) {
            return false;
        }

        String n = e.getName();

        if (n == null || n.isBlank()) {
            return false;
        }

        n = n.trim();

        if (n.matches("Q\\d+")) {
            return false;
        }

        // avoid absurd autogenerated labels
        if (n.length() > 120) {
            return false;
        }

        return true;
    }
}