package generic.buddy;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.implementation.MethodDelegation;
import net.bytebuddy.implementation.bind.annotation.Argument;
import net.bytebuddy.implementation.bind.annotation.RuntimeType;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import java.lang.reflect.Modifier;
import java.util.Map;

public class ByteBuddyExecutorFactory {

    public static CompiledValidator generate(ValidationConfig config) throws Exception {
        // Freeze a read-only copy of the active configuration map
        final Map<String, Object> frozenRules = Map.copyOf(config.getActiveRules());

        // This inner interceptor bridges ByteBuddy directly to our unrolled static execution engine
        Object interceptor = new Object() {
            @RuntimeType
            public boolean intercept(@Argument(0) UserRecord target) {
                return ValidationLogicBlueprint.evaluateRules(target, frozenRules);
            }
        };

        // Instruct ByteBuddy to assemble a raw class file in system RAM
        Class<? extends CompiledValidator> dynamicType = new ByteBuddy()
                .subclass(CompiledValidator.class)
                .name("generic.buddy.DynamicByteBuddyValidator")
                .method(net.bytebuddy.matcher.ElementMatchers.named("isValid"))
                .intercept(MethodDelegation.to(interceptor))
                .make()
                // UPDATE: Inject directly into the current classloader environment
                .load(ByteBuddyExecutorFactory.class.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                .getLoaded();
        // Instantiate the freshly generated bytecode executor class directly
        return dynamicType.getDeclaredConstructor().newInstance();
    }
}